import { StudyQuestion } from "@/lib/types";

export const SIMULATED_QUESTIONS: StudyQuestion[] = [
  {
    id: "sim-1",
    statement: "Qual servico AWS e recomendado para armazenar objetos com alta durabilidade e acesso por API?",
    certificationCode: "CLF-C02",
    topic: "S3",
    difficulty: "easy",
    options: {
      A: "Amazon EBS",
      B: "Amazon S3",
      C: "Amazon EFS",
      D: "AWS Backup",
      E: "Amazon EC2",
    },
    correctOption: "B",
    explanations: {
      A: "EBS e armazenamento em bloco para instancias EC2.",
      B: "S3 e armazenamento de objetos com alta durabilidade.",
      C: "EFS e sistema de arquivos compartilhado, nao objeto.",
      D: "AWS Backup e orquestracao de backup, nao storage principal de objeto.",
      E: "EC2 e computacao, nao servico de storage de objetos.",
    },
  },
  {
    id: "sim-2",
    statement: "Em um design altamente disponivel, qual pratica e mais adequada?",
    certificationCode: "CLF-C02",
    topic: "Arquitetura",
    difficulty: "medium",
    options: {
      A: "Usar uma unica AZ para simplificar operacao",
      B: "Distribuir carga entre multiplas AZs",
      C: "Desativar Auto Scaling para reduzir custos",
      D: "Concentrar todos os bancos em uma instancia",
      E: "Depender apenas de backup manual",
    },
    correctOption: "B",
    explanations: {
      A: "Uma unica AZ aumenta risco de indisponibilidade.",
      B: "Multi-AZ melhora resiliencia e disponibilidade.",
      C: "Auto Scaling ajuda disponibilidade e elasticidade.",
      D: "Centralizar tudo em um ponto aumenta risco de falha.",
      E: "Backup e importante, mas nao substitui arquitetura resiliente.",
    },
  },
  {
    id: "sim-3",
    statement: "Qual servico ajuda a controlar permissoes e identidade na AWS?",
    certificationCode: "CLF-C02",
    topic: "IAM",
    difficulty: "easy",
    options: {
      A: "Amazon CloudWatch",
      B: "AWS IAM",
      C: "Amazon Route 53",
      D: "AWS Shield",
      E: "Amazon Aurora",
    },
    correctOption: "B",
    explanations: {
      A: "CloudWatch e monitoramento, nao identidade.",
      B: "IAM gerencia usuarios, roles e politicas.",
      C: "Route 53 e DNS.",
      D: "Shield protege contra DDoS.",
      E: "Aurora e banco relacional.",
    },
  },
];

export const KC_QUESTIONS: StudyQuestion[] = [
  {
    id: "kc-ec2-1",
    statement: "No EC2, qual opcao melhora tolerancia a falhas de uma aplicacao web?",
    certificationCode: "SAA-C03",
    topic: "EC2",
    difficulty: "medium",
    options: {
      A: "Rodar em uma instancia sem Auto Scaling",
      B: "Usar Auto Scaling Group em multiplas AZs",
      C: "Desabilitar health checks",
      D: "Salvar sessoes apenas em disco local",
      E: "Fixar tudo em um unico subnet",
    },
    correctOption: "B",
    explanations: {
      A: "Uma unica instancia e ponto unico de falha.",
      B: "ASG multi-AZ aumenta disponibilidade e recuperacao automatica.",
      C: "Sem health checks, falhas demoram a ser detectadas.",
      D: "Disco local pode ser perdido em falha da instancia.",
      E: "Um unico subnet reduz resiliencia.",
    },
  },
  {
    id: "kc-iam-1",
    statement: "Qual e a melhor pratica para acesso de aplicacao a recursos AWS?",
    certificationCode: "SAA-C03",
    topic: "IAM",
    difficulty: "easy",
    options: {
      A: "Chave de acesso hardcoded no codigo",
      B: "Credenciais root para todos os servicos",
      C: "IAM Role com menor privilegio",
      D: "Senha compartilhada entre desenvolvedores",
      E: "Desabilitar MFA para simplificar",
    },
    correctOption: "C",
    explanations: {
      A: "Hardcode de chaves aumenta risco de vazamento.",
      B: "Conta root nao deve ser usada para operacoes do dia a dia.",
      C: "Roles com menor privilegio reduzem superficie de risco.",
      D: "Credenciais compartilhadas quebram rastreabilidade.",
      E: "MFA aumenta seguranca, nao deve ser removido.",
    },
  },
  {
    id: "kc-s3-1",
    statement: "Qual recurso do S3 ajuda a recuperar objetos apos exclusao acidental?",
    certificationCode: "SAA-C03",
    topic: "S3",
    difficulty: "easy",
    options: {
      A: "Versionamento",
      B: "S3 Transfer Acceleration",
      C: "Requester Pays",
      D: "Storage Lens",
      E: "Bucket policy publica",
    },
    correctOption: "A",
    explanations: {
      A: "Versionamento preserva versoes anteriores para recuperacao.",
      B: "Transfer Acceleration melhora transferencia de longa distancia.",
      C: "Requester Pays altera modelo de cobranca.",
      D: "Storage Lens e analise de uso.",
      E: "Acesso publico nao ajuda recuperacao.",
    },
  },
];
