import type { TriggerParams, TriggerType } from "@/lib/achievement-triggers";

export type AchievementDef = {
  code: string;
  name: string;
  description: string;
  rarity: "common" | "uncommon" | "rare" | "epic" | "legendary";
  target: number;
  displayOrder: number;
  prompt: string;
  triggerType: TriggerType;
  triggerParams: TriggerParams | null;
};

export const ACHIEVEMENT_DEFS: AchievementDef[] = [
  {
    code: "first_lab",
    name: "Primeiro Passo",
    description: "Concluir seu primeiro lab.",
    rarity: "common",
    target: 1,
    displayOrder: 1,
    prompt:
      "pixel-art badge, retro game style, bronze rank emblem, cloud icon, textless, warm colors, high contrast, aws learning journey",
    triggerType: "LAB_COUNT",
    triggerParams: null,
  },
  {
    code: "lab_master_10",
    name: "Mestre de Labs",
    description: "Concluir 10 labs.",
    rarity: "uncommon",
    target: 10,
    displayOrder: 2,
    prompt:
      "pixel-art badge, retro shield with 10 stars, cloud and terminal motifs, green/teal palette, textless, crisp icon",
    triggerType: "LAB_COUNT",
    triggerParams: null,
  },
  {
    code: "lab_master_25",
    name: "Veterano de Labs",
    description: "Concluir 25 labs.",
    rarity: "rare",
    target: 25,
    displayOrder: 3,
    prompt: "pixel-art badge, rare sapphire medal, lightning cloud symbol, arcade style, textless, polished edges",
    triggerType: "LAB_COUNT",
    triggerParams: null,
  },
  {
    code: "perfect_kc",
    name: "Especialista Perfeito",
    description: "Fazer 100% em um KC.",
    rarity: "rare",
    target: 1,
    displayOrder: 4,
    prompt: "pixel-art badge, perfect score trophy, checkmark + cloud, blue neon glow, retro game UI, textless",
    triggerType: "SESSION_SCORE_COUNT",
    triggerParams: { sessionType: "KC", minScorePercent: 100 },
  },
  {
    code: "simulado_aprovado",
    name: "Candidato Real",
    description: "Atingir 70% ou mais em um simulado.",
    rarity: "uncommon",
    target: 1,
    displayOrder: 5,
    prompt: "pixel-art badge, exam pass stamp, cloud and parchment, emerald accent, old-school style, textless",
    triggerType: "SESSION_SCORE_COUNT",
    triggerParams: { sessionType: "SIMULADO", minScorePercent: 70 },
  },
  {
    code: "simulado_veterano_5",
    name: "Veterano de Simulado",
    description: "Concluir 5 simulados.",
    rarity: "rare",
    target: 5,
    displayOrder: 6,
    prompt: "pixel-art badge, five marks exam insignia, cyber-retro style, blue and orange contrast, textless",
    triggerType: "SESSION_COUNT",
    triggerParams: { sessionType: "SIMULADO" },
  },
  {
    code: "knowledge_hunter_10",
    name: "Cacador de Conhecimento",
    description: "Concluir 10 KCs.",
    rarity: "rare",
    target: 10,
    displayOrder: 7,
    prompt: "pixel-art badge, hunter compass and cloud, vintage fantasy arcade style, cool hues, textless",
    triggerType: "SESSION_COUNT",
    triggerParams: { sessionType: "KC" },
  },
  {
    code: "xp_500",
    name: "Acumulador 500XP",
    description: "Alcancar 500 XP total.",
    rarity: "uncommon",
    target: 500,
    displayOrder: 8,
    prompt: "pixel-art badge, xp crystal shard icon, orange and teal glow, retro game inventory icon, textless",
    triggerType: "XP_TOTAL",
    triggerParams: null,
  },
  {
    code: "xp_2000",
    name: "Acumulador 2000XP",
    description: "Alcancar 2000 XP total.",
    rarity: "epic",
    target: 2000,
    displayOrder: 9,
    prompt: "pixel-art badge, epic crystal crown, magenta and cyan palette, dramatic arcade badge, textless",
    triggerType: "XP_TOTAL",
    triggerParams: null,
  },
  {
    code: "streak_3_days",
    name: "Ritmo Constante",
    description: "Manter uma sequencia de 3 dias de estudo.",
    rarity: "uncommon",
    target: 3,
    displayOrder: 10,
    prompt: "pixel-art badge, calendar flame icon, continuous streak motif, bright green accent, textless",
    triggerType: "STREAK_DAYS",
    triggerParams: null,
  },
  {
    code: "consistency_20_sessions",
    name: "Foco Continuo",
    description: "Concluir 20 sessoes de estudo (labs, KC ou simulados).",
    rarity: "epic",
    target: 20,
    displayOrder: 11,
    prompt: "pixel-art badge, disciplined warrior helm with cloud core, epic style, clean edges, textless",
    triggerType: "TOTAL_SESSIONS",
    triggerParams: null,
  },
  {
    code: "aws_legend",
    name: "Lenda AWS",
    description: "Somar 5000 XP e 5 simulados aprovados.",
    rarity: "legendary",
    target: 2,
    displayOrder: 12,
    prompt: "pixel-art legendary badge, radiant golden cloud dragon emblem, premium arcade icon, textless, high detail",
    triggerType: "XP_AND_SESSION_SCORE_COMBO",
    triggerParams: { xpThreshold: 5000, sessionType: "SIMULADO", minScorePercent: 70, sessionCountThreshold: 5 },
  },
  {
    code: "first_real_cert",
    name: "Certificado Real",
    description: "Registrar sua primeira certificacao AWS aprovada.",
    rarity: "epic",
    target: 1,
    displayOrder: 13,
    prompt: "pixel-art badge, golden aws certification stamp, diploma scroll with cloud seal, epic glow, textless",
    triggerType: "CERT_COUNT",
    triggerParams: null,
  },
  {
    code: "weekly_champion",
    name: "Campeao da Semana",
    description: "Terminar em 1o lugar no Desafio Semanal.",
    rarity: "legendary",
    target: 1,
    displayOrder: 14,
    prompt: "pixel-art legendary badge, golden laurel crown over cloud icon, radiant podium glow, textless, high detail",
    triggerType: "WEEKLY_CHALLENGE_WINS_COUNT",
    triggerParams: null,
  },
];
