import { createHmac } from "crypto";

// LGPD Art. 18 — right to object to processing for marketing purposes.
// Tokens are HMAC-signed (SHA-256) so they cannot be forged without the secret.
// TTL is embedded in the payload and verified on use.
//
// SYNC CONTRACT — this file has a deliberate duplicate in:
//   awlq-worker/src/shared/unsubscribe-token.ts
//
// Any change to the generation or validation logic (algorithm, payload shape,
// env var, encoding) MUST be applied to BOTH files simultaneously. Divergence
// will cause tokens generated by the worker to be unverifiable by the app,
// silently breaking the unsubscribe flow.

const ONE_YEAR_MS = 365 * 24 * 60 * 60 * 1000;

function getSecret(): string {
  const secret = process.env.BETTER_AUTH_SECRET;
  if (!secret) throw new Error("BETTER_AUTH_SECRET is not set");
  return secret;
}

function sign(payload: string): string {
  return createHmac("sha256", getSecret()).update(payload).digest("base64url");
}

/**
 * Generates a time-limited unsubscribe token for the given userId.
 * Format: base64url(JSON payload) . HMAC signature
 */
export function generateUnsubscribeToken(userId: string): string {
  const payload = JSON.stringify({ userId, exp: Date.now() + ONE_YEAR_MS });
  const encoded = Buffer.from(payload).toString("base64url");
  const signature = sign(encoded);
  return `${encoded}.${signature}`;
}

/**
 * Verifies an unsubscribe token and returns the userId it was issued for.
 * Returns null if the token is invalid, expired, or tampered with.
 */
export function verifyUnsubscribeToken(token: string): string | null {
  const dotIndex = token.lastIndexOf(".");
  if (dotIndex === -1) return null;

  const encoded = token.slice(0, dotIndex);
  const providedSig = token.slice(dotIndex + 1);
  const expectedSig = sign(encoded);

  // Constant-time comparison to prevent timing attacks
  if (providedSig.length !== expectedSig.length) return null;
  let diff = 0;
  for (let i = 0; i < providedSig.length; i++) {
    diff |= providedSig.charCodeAt(i) ^ expectedSig.charCodeAt(i);
  }
  if (diff !== 0) return null;

  let parsed: { userId?: string; exp?: number };
  try {
    parsed = JSON.parse(Buffer.from(encoded, "base64url").toString()) as {
      userId?: string;
      exp?: number;
    };
  } catch {
    return null;
  }

  if (!parsed.userId || typeof parsed.exp !== "number") return null;
  if (Date.now() > parsed.exp) return null;

  return parsed.userId;
}
