import { createHmac } from "crypto";

// SYNC CONTRACT — this file is a deliberate duplicate of:
//   awlq-app/src/lib/unsubscribe-token.ts
//
// The two projects share no package boundary, so the token logic is copied
// rather than imported. Any change to the generation or validation logic
// (algorithm, payload shape, env var, encoding) MUST be applied to BOTH files
// simultaneously. Divergence will cause tokens generated by the worker to be
// unverifiable by the app, silently breaking the unsubscribe flow.

const ONE_YEAR_MS = 365 * 24 * 60 * 60 * 1000;

function getSecret(): string {
  const secret = process.env.BETTER_AUTH_SECRET;
  if (!secret) throw new Error("BETTER_AUTH_SECRET is not set");
  return secret;
}

function sign(payload: string): string {
  return createHmac("sha256", getSecret()).update(payload).digest("base64url");
}

export function generateUnsubscribeToken(userId: string): string {
  const payload = JSON.stringify({ userId, exp: Date.now() + ONE_YEAR_MS });
  const encoded = Buffer.from(payload).toString("base64url");
  const signature = sign(encoded);
  return `${encoded}.${signature}`;
}
